"use client";
import { type FormEvent, useMemo, useState } from "react";
import { BadgeCheck, Check, Copy, Loader2, RotateCcw, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/shared/badge";
import { PLATFORM_DEFINITIONS } from "@/lib/creator-platforms";
import type { CreatorCardData } from "@/lib/types";

export function CreatorVerificationCard({ creator }: { creator: CreatorCardData | null }) {
  const accounts = useMemo(() => creator?.platformAccounts ?? [], [creator?.platformAccounts]);
  const [accountId, setAccountId] = useState(accounts.find((account) => account.verification.status !== "verified")?.id ?? accounts[0]?.id ?? "");
  const [code, setCode] = useState(""); const [expiresAt, setExpiresAt] = useState(""); const [note, setNote] = useState("");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<{ error?: string; success?: string }>({}); const [copied, setCopied] = useState(false);
  const account = useMemo(() => accounts.find((item) => item.id === accountId), [accountId, accounts]);
  async function generate() { setBusy(true); setMessage({}); try { const response = await fetch("/api/creator-verification/status", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ platformAccountId: accountId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not generate a verification code."); setCode(result.verificationCode); setExpiresAt(result.expiresAt); setMessage({ success: "A new code was generated. Any previous code for this account is now invalid." }); } catch (error) { setMessage({ error: error instanceof Error ? error.message : "Could not generate a verification code." }); } finally { setBusy(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage({}); try { const response = await fetch("/api/creator-verification/submit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ platformAccountId: accountId, note }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not submit verification."); setCode(""); setMessage({ success: "This platform account was submitted for admin review." }); } catch (error) { setMessage({ error: error instanceof Error ? error.message : "Could not submit verification." }); } finally { setBusy(false); } }
  async function copy() { if (!code) return; try { await navigator.clipboard.writeText(code); setCopied(true); window.setTimeout(() => setCopied(false), 1500); } catch { setMessage({ error: "Could not copy the code. Select and copy it manually." }); } }
  return <section id="platform-verification" className="rounded-[8px] border border-white/10 bg-white/[0.04] p-5">
    <div className="flex items-start justify-between gap-3"><div><p className="bridge-eyebrow">Branzzo</p><h2 className="mt-2 font-display text-2xl font-bold">Platform verification</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Generate a private one-time code for one saved account, place it in that public profile, then submit it for review.</p></div><ShieldCheck size={22} className="text-cyan-100" /></div>
    {message.error ? <div role="alert" className="mt-4 rounded-[8px] border border-red-900 bg-red-950/40 p-3 text-sm text-red-200">{message.error}</div> : null}{message.success ? <div role="status" className="mt-4 rounded-[8px] border border-emerald-800 bg-emerald-950/40 p-3 text-sm text-emerald-100">{message.success}</div> : null}
    {!accounts.length ? <p className="mt-5 text-sm text-[var(--text-secondary)]">Add a platform account before requesting verification.</p> : <form onSubmit={submit} className="mt-5 grid gap-4">
      <label><span className="bridge-label">Platform account</span><select value={accountId} onChange={(event) => { setAccountId(event.target.value); setCode(""); }} className="bridge-input mt-2">{accounts.map((item) => <option key={item.id} value={item.id}>{item.platform === "other" ? item.customPlatformName || "Other" : PLATFORM_DEFINITIONS[item.platform].label} · {item.handle || item.profileUrl}</option>)}</select></label>
      {account ? <div className="flex flex-wrap gap-2"><Badge tone={account.verification.status === "verified" ? "green" : account.verification.status === "pending" ? "yellow" : "neutral"}>{account.verification.status}</Badge><a href={account.profileUrl} target="_blank" rel="noopener noreferrer" className="text-sm text-cyan-100 underline">Open saved profile</a></div> : null}
      {account?.verification.status !== "verified" ? <><button type="button" onClick={generate} disabled={busy || !accountId} className="bridge-button-secondary w-full"><RotateCcw size={16} />{code ? "Regenerate code" : "Generate code"}</button>{code ? <div className="rounded-[8px] border border-cyan-300/20 bg-cyan-300/10 p-4"><p className="bridge-label">Shown once</p><div className="mt-2 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><code className="break-all text-xl font-bold">{code}</code><button type="button" onClick={copy} className="bridge-button-secondary"><Copy size={15} />{copied ? <><Check size={14} />Copied</> : "Copy"}</button></div><p className="mt-2 text-xs text-[var(--text-secondary)]">Expires {new Date(expiresAt).toLocaleString()}. It cannot be recovered; regenerate if lost.</p></div> : null}<label><span className="bridge-label">Optional review note</span><textarea maxLength={500} value={note} onChange={(event) => setNote(event.target.value)} className="bridge-input mt-2 min-h-20" /></label><button type="submit" disabled={busy || !code} className="bridge-button-primary w-full">{busy ? <Loader2 size={16} className="animate-spin" /> : <BadgeCheck size={16} />}Submit for review</button></> : <p className="text-sm text-emerald-100">This account is verified.</p>}
    </form>}
  </section>;
}
