import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect, test } from "@playwright/test";
import { creatorVerificationExpiry, generateCreatorVerificationCode, hashCreatorVerificationCode, isCreatorVerificationExpired, matchesCreatorVerificationCode } from "../../lib/creator-verification";
import { createCollaborationPlatformSnapshot, deriveAudience, legacyPlatformAccounts, preparePlatformAccounts } from "../../lib/creator-platforms";
import { CreatorVerificationRequest } from "../../lib/models/CreatorVerificationRequest";

test("verification codes are random, hashed, expiring and safely comparable", () => { const first = generateCreatorVerificationCode(); const second = generateCreatorVerificationCode(); expect(first).not.toBe(second); const encoded = hashCreatorVerificationCode(first); expect(encoded.hash).not.toContain(first); expect(matchesCreatorVerificationCode(first, encoded.salt, encoded.hash)).toBe(true); expect(matchesCreatorVerificationCode(second, encoded.salt, encoded.hash)).toBe(false); const expiry = creatorVerificationExpiry(new Date(0)); expect(expiry.getTime()).toBe(86_400_000); expect(isCreatorVerificationExpired(expiry, new Date(86_400_001))).toBe(true); });
test("verification request persistence has no plaintext code field", () => { expect(CreatorVerificationRequest.schema.path("verificationCode")).toBeUndefined(); expect(CreatorVerificationRequest.schema.path("codeHash")?.options.select).toBe(false); expect(CreatorVerificationRequest.schema.path("codeSalt")?.options.select).toBe(false); });
test("editing accounts keeps one primary and recalculates after maximum removal", () => { const accounts = preparePlatformAccounts([{ id: "ig", platform: "instagram", customPlatformName: "", handle: "", profileUrl: "https://instagram.com/a", audienceType: "followers", audienceCount: 100_000, isPrimary: true }, { id: "yt", platform: "youtube", customPlatformName: "", handle: "", profileUrl: "https://youtube.com/@a", audienceType: "subscribers", audienceCount: 200_000, isPrimary: false }], new Set(["ig", "yt"])); expect(accounts.filter((account) => account.isPrimary)).toHaveLength(1); expect(deriveAudience(accounts).topAudienceCount).toBe(200_000); expect(deriveAudience(accounts.filter((account) => account.id !== "yt")).topAudienceCount).toBe(100_000); });
test("collaboration snapshot is server-derived, stable and campaign eligible", () => { const profile = { platformAccounts: [{ id: "ig", platform: "instagram", profileUrl: "https://instagram.com/a", normalizedProfileUrl: "https://instagram.com/a", audienceType: "followers", audienceCount: 20, isPrimary: true, verification: { status: "verified" } }, { id: "kick", platform: "kick", profileUrl: "https://kick.com/a", normalizedProfileUrl: "https://kick.com/a", audienceType: "followers", audienceCount: 50, isPrimary: false, verification: { status: "unverified" } }] }; const snapshot = createCollaborationPlatformSnapshot(profile, ["kick"]); expect(snapshot).toMatchObject({ platformAccountId: "kick", platform: "kick", audienceCount: 50, verificationStatus: "unverified" }); profile.platformAccounts[1].audienceCount = 999; expect(snapshot?.audienceCount).toBe(50); });
test("legacy conversion preserves verified state, rejects invalid URLs and is idempotent", () => { const legacy = legacyPlatformAccounts({ youtubeUrl: "https://youtube.com/@a", subscribers: 10, verificationStatus: "verified", instagramUrl: "javascript:alert(1)" }); expect(legacy).toHaveLength(1); expect(legacy[0].verification.status).toBe("verified"); expect(legacyPlatformAccounts({ platformAccounts: legacy })).toEqual(legacy); });
test("founding allocation returns the incremented counter document without deprecated options", () => { const source = readFileSync(resolve(process.cwd(), "lib/founding-creators.ts"), "utf8"); expect(source).toContain('returnDocument: "after"'); expect(source).not.toContain("new: true"); });
